### ISSUE TITLE
Encrypt secrets

### ISSUE THREAD

**Issue by Asdew95** [TestudoAquatilis/totp#3]
I really like this, but the secrets should be encrypted with a user-defined password with a strong encryptiong algorithm.

**Comment by TestudoAquatilis** [comment]
This is a valid complaint...
Our original reason for this helper script was to just have a simple way to login to certain services requiring a TOTP login where we could remember our passwords and did not want to unlock our keepass for every login and where we trust our local machines more than a smartphone (where I think these are also stored without need for a password to unlock).

So this might be a good addon feature, although probably not in the near future.
But as this is indeed something important, I added a warning in the readme for the meantime.

**Comment by TestudoAquatilis** [comment]
we now added a way to use gpg to password-encrypt the secret if wanted - and switches for adding/modifying/deleteing secrets...
so totp -g -a <identifier> will add a gpg-crypted entry for <indentifier>. This sources out the strong encryption to gpg which probably is well suited for this.
Possible disadvantage (or maybe advantage): every identifier has its own encryption setting/password.
So I would mark it as solved: 8110eeafdc1a5c38006cdf245afc3d667e0a58fb
